### PR TITLE
Input added

### PR DESCRIPTION
**Pull request by sakshamAK**

### CODE REVIEW

**Comment by nshanbhag20001412** [comment]
looks good to me. Suggestion: At some places, you have defined colors directly, you can use color variables for that.

**Review by nshanbhag20001412 — APPROVED** [review]
Keep it up saksham

**Review by himadri2110 — APPROVED** [review]
Hey, looks like you forgot to change the title of the Input page. It shows 'Image'. 

Rest all looks good!

**Comment by sakshamAK** [comment]
> 

sure, thanks for pointing it out

**Comment by sakshamAK** [comment]
> looks good to me. Suggestion: At some places, you have defined colors directly, you can use color variables for that.

sure, thanks

**Review by mimansha-swarup — APPROVED** [review]
Looks good to me

**Review by nshanbhag20001412 — APPROVED** [review]

**Pull request merged**
